### ISSUE TITLE
unix domain socket /tmp/.s.pgsql.5432 error

### ISSUE THREAD

**Issue by VJPrasad** [greenplum-db/gpdb-sandbox-tutorials#17]
Hi,

I am receiving the following error while using the psql command:
is the server running locally and accepting connections on unix domain socket /tmp/.s.pgsql.5432

How to go about resolving this issue?

Thanks

**Comment by danielgustafsson** [comment]
Please raise questions like this one on the gpdb-users mailinglist, see http://greenplum.org/#mailing-lists for more information.
