### ISSUE TITLE
Apache Zeppelin lesson

### ISSUE THREAD

**Issue by mandolyte** [greenplum-db/gpdb-sandbox-tutorials#9]
I am unable to connect because I am prompted for user name and password. I tried both gpadmin and gpmon, but neither work. What should be entered?
Thanks!
![image](https://cloud.githubusercontent.com/assets/1289437/11538642/db694384-98f0-11e5-8c97-e7fcf31af9b8.png)

**Comment by mandolyte** [comment]
This may be caused by something else running and using that port, since I just just down the VM and I still get the prompt. Not sure what it might be, but I do a lot experimenting, so it may be left overs. Where can I change the port that it using?

**Comment by dbbaskette** [comment]
Hmmm...that's a new one.  Never had it ask.   fusion or box?

**Comment by mandolyte** [comment]
Box... but I may just need to change the port it is using (see previous comment). Where can I make that change?

**Comment by dbbaskette** [comment]
Ok, the file is in /user/local/<Zeppelin Dir>/conf.   It's Zeppelin-site.xml.      The issue must be in my BOX version.   I tested the labs on Fusion.

**Comment by mandolyte** [comment]
I only find a template for this XML file. Does it have a different name?
![image](https://cloud.githubusercontent.com/assets/1289437/11541954/1288efec-9903-11e5-9f05-54f69c6a6b1d.png)

**Comment by dbbaskette** [comment]
Rename it to remove template and then make the change.

**Comment by mandolyte** [comment]
I removed the existing OVA and re-imported from scratch and started the VM. Then I used SSH to connect and made the edits. I then pointed my browser to localhost:8090 and it gave me:

```
This webpage is not available

ERR_CONNECTION_REFUSED
```

I have attached a transcript of this in case it helps. Near the end I show the XML as edited.
[transcript.txt](https://github.com/greenplum-db/gpdb-sandbox-tutorials/files/51244/transcript.txt)

**Comment by dbbaskette** [comment]
VirtualBox requires you to setup NAT for all ports.   If you check your Network settings you will see the ones already created and you can just make the change.    I will dig into this early next week.

**Comment by dbbaskette** [comment]
I tested it and it works fine for me, so it looks like you must have another app on 8080 like you mentioned.     Go into your settings for the VM and Choose Network, Advanced (on NAT).  Click Port Forwarding and change the Host port and if you changed the Zeppelin default port change the guest port as well.

**Comment by mandolyte** [comment]
Worked beautifully! thanks for the help.
